//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllerRetour
    {
        public int AR_ID { get; set; }
        public int AR_ALLER_RES_ID { get; set; }
        public Nullable<int> AR_RETOUR_RES_ID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Reservation Reservation1 { get; set; }
    }
}
