//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlinesEntities : DbContext
    {
        public AirlinesEntities()
            : base("name=AirlinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accompagnateur> Accompagnateur { get; set; }
        public virtual DbSet<AllerRetour> AllerRetour { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Planning> Planning { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tranche> Tranche { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
        public virtual DbSet<Vol> Vol { get; set; }
    
        public virtual ObjectResult<PLAN_FetchListePassagers_Result> PLAN_FetchListePassagers(Nullable<int> idVol, Nullable<int> idPlan)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanParameter = idPlan.HasValue ?
                new ObjectParameter("IdPlan", idPlan) :
                new ObjectParameter("IdPlan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLAN_FetchListePassagers_Result>("PLAN_FetchListePassagers", idVolParameter, idPlanParameter);
        }
    
        public virtual ObjectResult<PRI_FetchPrixTranchesVol_Result> PRI_FetchPrixTranchesVol(Nullable<int> idVol)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRI_FetchPrixTranchesVol_Result>("PRI_FetchPrixTranchesVol", idVolParameter);
        }
    
        public virtual ObjectResult<Vol_FetchVolInfos_Result> Vol_FetchVolInfos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vol_FetchVolInfos_Result>("Vol_FetchVolInfos");
        }
    
        public virtual ObjectResult<VOL_FiltrerResultats_Result> VOL_FiltrerResultats(string input)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_FiltrerResultats_Result>("VOL_FiltrerResultats", inputParameter);
        }
    
        public virtual ObjectResult<VOL_GetCaParAge_Result> VOL_GetCaParAge(Nullable<int> idPlan)
        {
            var idPlanParameter = idPlan.HasValue ?
                new ObjectParameter("IdPlan", idPlan) :
                new ObjectParameter("IdPlan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_GetCaParAge_Result>("VOL_GetCaParAge", idPlanParameter);
        }
    
        public virtual int VOL_PLA_FetchStatistics(Nullable<int> idVol, Nullable<int> idPlan, ObjectParameter nbPassagers, ObjectParameter nbPlacesRestantes, ObjectParameter tauxOccupation, Nullable<int> nbClients, Nullable<int> nbAccompagnateurs, Nullable<int> nbPlacesDispo, Nullable<System.DateTime> dateNaissance, Nullable<System.DateTime> dateVol, Nullable<int> fetchOuter, Nullable<int> fetchInner, Nullable<int> age, ObjectParameter ca, Nullable<decimal> caTmp, Nullable<int> idClient, Nullable<int> idRes)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanParameter = idPlan.HasValue ?
                new ObjectParameter("IdPlan", idPlan) :
                new ObjectParameter("IdPlan", typeof(int));
    
            var nbClientsParameter = nbClients.HasValue ?
                new ObjectParameter("NbClients", nbClients) :
                new ObjectParameter("NbClients", typeof(int));
    
            var nbAccompagnateursParameter = nbAccompagnateurs.HasValue ?
                new ObjectParameter("NbAccompagnateurs", nbAccompagnateurs) :
                new ObjectParameter("NbAccompagnateurs", typeof(int));
    
            var nbPlacesDispoParameter = nbPlacesDispo.HasValue ?
                new ObjectParameter("NbPlacesDispo", nbPlacesDispo) :
                new ObjectParameter("NbPlacesDispo", typeof(int));
    
            var dateNaissanceParameter = dateNaissance.HasValue ?
                new ObjectParameter("DateNaissance", dateNaissance) :
                new ObjectParameter("DateNaissance", typeof(System.DateTime));
    
            var dateVolParameter = dateVol.HasValue ?
                new ObjectParameter("DateVol", dateVol) :
                new ObjectParameter("DateVol", typeof(System.DateTime));
    
            var fetchOuterParameter = fetchOuter.HasValue ?
                new ObjectParameter("FetchOuter", fetchOuter) :
                new ObjectParameter("FetchOuter", typeof(int));
    
            var fetchInnerParameter = fetchInner.HasValue ?
                new ObjectParameter("FetchInner", fetchInner) :
                new ObjectParameter("FetchInner", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var caTmpParameter = caTmp.HasValue ?
                new ObjectParameter("CaTmp", caTmp) :
                new ObjectParameter("CaTmp", typeof(decimal));
    
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idResParameter = idRes.HasValue ?
                new ObjectParameter("IdRes", idRes) :
                new ObjectParameter("IdRes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VOL_PLA_FetchStatistics", idVolParameter, idPlanParameter, nbPassagers, nbPlacesRestantes, tauxOccupation, nbClientsParameter, nbAccompagnateursParameter, nbPlacesDispoParameter, dateNaissanceParameter, dateVolParameter, fetchOuterParameter, fetchInnerParameter, ageParameter, ca, caTmpParameter, idClientParameter, idResParameter);
        }
    
        public virtual ObjectResult<VOL_TousLesVols_Result> VOL_TousLesVols()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_TousLesVols_Result>("VOL_TousLesVols");
        }
    
        public virtual ObjectResult<CLI_FetchTousClients_Result> CLI_FetchTousClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLI_FetchTousClients_Result>("CLI_FetchTousClients");
        }
    
        public virtual ObjectResult<Client_Add_Result> Client_Add()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_Add_Result>("Client_Add");
        }
    
        public virtual int ACC_DeleteAccompagnateur(Nullable<int> idAccompagnateur)
        {
            var idAccompagnateurParameter = idAccompagnateur.HasValue ?
                new ObjectParameter("IdAccompagnateur", idAccompagnateur) :
                new ObjectParameter("IdAccompagnateur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_DeleteAccompagnateur", idAccompagnateurParameter);
        }
    
        public virtual int ACC_DeleteByResId(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_DeleteByResId", idReservationParameter);
        }
    
        public virtual ObjectResult<ACC_GetAccompagnateurChiffreParTete_Result> ACC_GetAccompagnateurChiffreParTete(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACC_GetAccompagnateurChiffreParTete_Result>("ACC_GetAccompagnateurChiffreParTete", idReservationParameter);
        }
    
        public virtual ObjectResult<ACC_GetAccompagnateursWithPrice_Result> ACC_GetAccompagnateursWithPrice(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACC_GetAccompagnateursWithPrice_Result>("ACC_GetAccompagnateursWithPrice", idReservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ACC_GetAccResId(Nullable<int> idAccompagnateur)
        {
            var idAccompagnateurParameter = idAccompagnateur.HasValue ?
                new ObjectParameter("IdAccompagnateur", idAccompagnateur) :
                new ObjectParameter("IdAccompagnateur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ACC_GetAccResId", idAccompagnateurParameter);
        }
    
        public virtual int ACC_Insert(string nom, string prenom, Nullable<System.DateTime> dateNaissance, Nullable<int> idReservation)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var prenomParameter = prenom != null ?
                new ObjectParameter("Prenom", prenom) :
                new ObjectParameter("Prenom", typeof(string));
    
            var dateNaissanceParameter = dateNaissance.HasValue ?
                new ObjectParameter("DateNaissance", dateNaissance) :
                new ObjectParameter("DateNaissance", typeof(System.DateTime));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_Insert", nomParameter, prenomParameter, dateNaissanceParameter, idReservationParameter);
        }
    
        public virtual int ACC_InsertNullPrenom(string nom, Nullable<System.DateTime> dateNaissance, Nullable<int> idReservation)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var dateNaissanceParameter = dateNaissance.HasValue ?
                new ObjectParameter("DateNaissance", dateNaissance) :
                new ObjectParameter("DateNaissance", typeof(System.DateTime));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_InsertNullPrenom", nomParameter, dateNaissanceParameter, idReservationParameter);
        }
    
        public virtual int AR_DeleteARById(Nullable<int> idAr)
        {
            var idArParameter = idAr.HasValue ?
                new ObjectParameter("IdAr", idAr) :
                new ObjectParameter("IdAr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AR_DeleteARById", idArParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AR_GetArId(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AR_GetArId", idReservationParameter);
        }
    
        public virtual int AR_InsertAR(Nullable<int> idReservationAller, Nullable<int> idReservationRetour)
        {
            var idReservationAllerParameter = idReservationAller.HasValue ?
                new ObjectParameter("IdReservationAller", idReservationAller) :
                new ObjectParameter("IdReservationAller", typeof(int));
    
            var idReservationRetourParameter = idReservationRetour.HasValue ?
                new ObjectParameter("IdReservationRetour", idReservationRetour) :
                new ObjectParameter("IdReservationRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AR_InsertAR", idReservationAllerParameter, idReservationRetourParameter);
        }
    
        public virtual ObjectResult<CLI_GetClientMoneyInfo_Result> CLI_GetClientMoneyInfo(Nullable<int> idClient, Nullable<int> idReservation)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLI_GetClientMoneyInfo_Result>("CLI_GetClientMoneyInfo", idClientParameter, idReservationParameter);
        }
    
        public virtual ObjectResult<CLI_SelectAll_Result> CLI_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLI_SelectAll_Result>("CLI_SelectAll");
        }
    
        public virtual ObjectResult<Client_Add1_Result> Client_Add1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_Add1_Result>("Client_Add1");
        }
    
        public virtual ObjectResult<PLA_GetDateByVolId_Result> PLA_GetDateByVolId(Nullable<int> idVol)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDateByVolId_Result>("PLA_GetDateByVolId", idVolParameter);
        }
    
        public virtual ObjectResult<PLA_GetDateByVolIdDateCritere_Result> PLA_GetDateByVolIdDateCritere(Nullable<int> idVol, Nullable<System.DateTime> date)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDateByVolIdDateCritere_Result>("PLA_GetDateByVolIdDateCritere", idVolParameter, dateParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> PLA_GetDatesMemeVol(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("PLA_GetDatesMemeVol", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<PLA_GetDatesMemeVolWithPlaId_Result> PLA_GetDatesMemeVolWithPlaId(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDatesMemeVolWithPlaId_Result>("PLA_GetDatesMemeVolWithPlaId", idVolParameter, idPlanningParameter);
        }
    
        public virtual int RES_DeleteResId(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_DeleteResId", idReservationParameter);
        }
    
        public virtual ObjectResult<RES_GetAller_Result> RES_GetAller(Nullable<System.DateTime> date, Nullable<int> idClient, Nullable<int> idVilleDepart, Nullable<int> idVilleRetour)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idVilleDepartParameter = idVilleDepart.HasValue ?
                new ObjectParameter("IdVilleDepart", idVilleDepart) :
                new ObjectParameter("IdVilleDepart", typeof(int));
    
            var idVilleRetourParameter = idVilleRetour.HasValue ?
                new ObjectParameter("IdVilleRetour", idVilleRetour) :
                new ObjectParameter("IdVilleRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RES_GetAller_Result>("RES_GetAller", dateParameter, idClientParameter, idVilleDepartParameter, idVilleRetourParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> RES_GetPrixTotal(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("RES_GetPrixTotal", idReservationParameter);
        }
    
        public virtual ObjectResult<RES_GetResByClientId_Result> RES_GetResByClientId(Nullable<int> idClient)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RES_GetResByClientId_Result>("RES_GetResByClientId", idClientParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RES_GetResId(Nullable<int> idClient, Nullable<int> idPlanning)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RES_GetResId", idClientParameter, idPlanningParameter);
        }
    
        public virtual int RES_Insert(Nullable<int> idClient, Nullable<int> idPlanning)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_Insert", idClientParameter, idPlanningParameter);
        }
    
        public virtual int RES_UpdateReservationResId(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_UpdateReservationResId", idReservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VOL_PLA_GetNbPlacesRestantesNEW(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VOL_PLA_GetNbPlacesRestantesNEW", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<VOL_SelectAllListChoix_Result> VOL_SelectAllListChoix()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_SelectAllListChoix_Result>("VOL_SelectAllListChoix");
        }
    
        public virtual ObjectResult<VOL_SelectAllListChoixRetour_Result> VOL_SelectAllListChoixRetour(Nullable<int> idVilleDepart, Nullable<int> idVilleRetour)
        {
            var idVilleDepartParameter = idVilleDepart.HasValue ?
                new ObjectParameter("IdVilleDepart", idVilleDepart) :
                new ObjectParameter("IdVilleDepart", typeof(int));
    
            var idVilleRetourParameter = idVilleRetour.HasValue ?
                new ObjectParameter("IdVilleRetour", idVilleRetour) :
                new ObjectParameter("IdVilleRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_SelectAllListChoixRetour_Result>("VOL_SelectAllListChoixRetour", idVilleDepartParameter, idVilleRetourParameter);
        }
    
        public virtual int ACC_DeleteAccompagnateur1(Nullable<int> idAccompagnateur)
        {
            var idAccompagnateurParameter = idAccompagnateur.HasValue ?
                new ObjectParameter("IdAccompagnateur", idAccompagnateur) :
                new ObjectParameter("IdAccompagnateur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_DeleteAccompagnateur1", idAccompagnateurParameter);
        }
    
        public virtual int ACC_DeleteByResId1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_DeleteByResId1", idReservationParameter);
        }
    
        public virtual ObjectResult<ACC_GetAccompagnateurChiffreParTete1_Result> ACC_GetAccompagnateurChiffreParTete1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACC_GetAccompagnateurChiffreParTete1_Result>("ACC_GetAccompagnateurChiffreParTete1", idReservationParameter);
        }
    
        public virtual ObjectResult<ACC_GetAccompagnateursWithPrice1_Result> ACC_GetAccompagnateursWithPrice1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACC_GetAccompagnateursWithPrice1_Result>("ACC_GetAccompagnateursWithPrice1", idReservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ACC_GetVoyResId(Nullable<int> idAccompagnateur)
        {
            var idAccompagnateurParameter = idAccompagnateur.HasValue ?
                new ObjectParameter("IdAccompagnateur", idAccompagnateur) :
                new ObjectParameter("IdAccompagnateur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ACC_GetVoyResId", idAccompagnateurParameter);
        }
    
        public virtual int ACC_Insert1(string nom, string prenom, Nullable<System.DateTime> dateNaissance, Nullable<int> idReservation)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var prenomParameter = prenom != null ?
                new ObjectParameter("Prenom", prenom) :
                new ObjectParameter("Prenom", typeof(string));
    
            var dateNaissanceParameter = dateNaissance.HasValue ?
                new ObjectParameter("DateNaissance", dateNaissance) :
                new ObjectParameter("DateNaissance", typeof(System.DateTime));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_Insert1", nomParameter, prenomParameter, dateNaissanceParameter, idReservationParameter);
        }
    
        public virtual int ACC_InsertNullPrenom1(string nom, Nullable<System.DateTime> dateNaissance, Nullable<int> idReservation)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var dateNaissanceParameter = dateNaissance.HasValue ?
                new ObjectParameter("DateNaissance", dateNaissance) :
                new ObjectParameter("DateNaissance", typeof(System.DateTime));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACC_InsertNullPrenom1", nomParameter, dateNaissanceParameter, idReservationParameter);
        }
    
        public virtual int AR_DeleteARById1(Nullable<int> arId)
        {
            var arIdParameter = arId.HasValue ?
                new ObjectParameter("ArId", arId) :
                new ObjectParameter("ArId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AR_DeleteARById1", arIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AR_GetArId1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AR_GetArId1", idReservationParameter);
        }
    
        public virtual int AR_InsertAR1(Nullable<int> idReservationAller, Nullable<int> idReservationRetour)
        {
            var idReservationAllerParameter = idReservationAller.HasValue ?
                new ObjectParameter("IdReservationAller", idReservationAller) :
                new ObjectParameter("IdReservationAller", typeof(int));
    
            var idReservationRetourParameter = idReservationRetour.HasValue ?
                new ObjectParameter("IdReservationRetour", idReservationRetour) :
                new ObjectParameter("IdReservationRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AR_InsertAR1", idReservationAllerParameter, idReservationRetourParameter);
        }
    
        public virtual ObjectResult<CLI_GetClientMoneyInfo1_Result> CLI_GetClientMoneyInfo1(Nullable<int> cli_Id, Nullable<int> idReservation)
        {
            var cli_IdParameter = cli_Id.HasValue ?
                new ObjectParameter("Cli_Id", cli_Id) :
                new ObjectParameter("Cli_Id", typeof(int));
    
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLI_GetClientMoneyInfo1_Result>("CLI_GetClientMoneyInfo1", cli_IdParameter, idReservationParameter);
        }
    
        public virtual ObjectResult<CLI_SelectAll1_Result> CLI_SelectAll1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CLI_SelectAll1_Result>("CLI_SelectAll1");
        }
    
        public virtual ObjectResult<Nullable<int>> DELETE___ACC_GetAccompagnateursWithPF(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DELETE___ACC_GetAccompagnateursWithPF", idReservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DELETE___ACC_GetAccompagnateursWithPFF(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DELETE___ACC_GetAccompagnateursWithPFF", idReservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DELETE___ACC_GetAccompagnateursWithPriceFetch(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DELETE___ACC_GetAccompagnateursWithPriceFetch", idReservationParameter);
        }
    
        public virtual int DELETE___ACC_UpdateAccompagnateur(string nom, string prenom, Nullable<System.DateTime> date, Nullable<int> idAccompagnateur)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("Nom", nom) :
                new ObjectParameter("Nom", typeof(string));
    
            var prenomParameter = prenom != null ?
                new ObjectParameter("Prenom", prenom) :
                new ObjectParameter("Prenom", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var idAccompagnateurParameter = idAccompagnateur.HasValue ?
                new ObjectParameter("IdAccompagnateur", idAccompagnateur) :
                new ObjectParameter("IdAccompagnateur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE___ACC_UpdateAccompagnateur", nomParameter, prenomParameter, dateParameter, idAccompagnateurParameter);
        }
    
        public virtual ObjectResult<DELETE___VOL_SelectAllListChoixRetourContrainteDate_Result> DELETE___VOL_SelectAllListChoixRetourContrainteDate(Nullable<int> idVilleDepart, Nullable<int> idVilleRetour, Nullable<System.DateTime> date)
        {
            var idVilleDepartParameter = idVilleDepart.HasValue ?
                new ObjectParameter("IdVilleDepart", idVilleDepart) :
                new ObjectParameter("IdVilleDepart", typeof(int));
    
            var idVilleRetourParameter = idVilleRetour.HasValue ?
                new ObjectParameter("IdVilleRetour", idVilleRetour) :
                new ObjectParameter("IdVilleRetour", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DELETE___VOL_SelectAllListChoixRetourContrainteDate_Result>("DELETE___VOL_SelectAllListChoixRetourContrainteDate", idVilleDepartParameter, idVilleRetourParameter, dateParameter);
        }
    
        public virtual ObjectResult<PLA_GetDateByVolId1_Result> PLA_GetDateByVolId1(Nullable<int> idVol)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDateByVolId1_Result>("PLA_GetDateByVolId1", idVolParameter);
        }
    
        public virtual ObjectResult<PLA_GetDateByVolIdDateCritere1_Result> PLA_GetDateByVolIdDateCritere1(Nullable<int> idVol, Nullable<System.DateTime> date)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDateByVolIdDateCritere1_Result>("PLA_GetDateByVolIdDateCritere1", idVolParameter, dateParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> PLA_GetDatesMemeVol1(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("PLA_GetDatesMemeVol1", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<PLA_GetDatesMemeVolWithPlaId1_Result> PLA_GetDatesMemeVolWithPlaId1(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDatesMemeVolWithPlaId1_Result>("PLA_GetDatesMemeVolWithPlaId1", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<PLA_GetListePassagers_Result> PLA_GetListePassagers(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetListePassagers_Result>("PLA_GetListePassagers", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<PRI_GetPrixByVol_Result> PRI_GetPrixByVol(Nullable<int> idVol)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRI_GetPrixByVol_Result>("PRI_GetPrixByVol", idVolParameter);
        }
    
        public virtual int RES_DeleteResId1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_DeleteResId1", idReservationParameter);
        }
    
        public virtual ObjectResult<RES_GetAller1_Result> RES_GetAller1(Nullable<System.DateTime> date, Nullable<int> idClient, Nullable<int> idVilleDepart, Nullable<int> idVilleRetour)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idVilleDepartParameter = idVilleDepart.HasValue ?
                new ObjectParameter("IdVilleDepart", idVilleDepart) :
                new ObjectParameter("IdVilleDepart", typeof(int));
    
            var idVilleRetourParameter = idVilleRetour.HasValue ?
                new ObjectParameter("IdVilleRetour", idVilleRetour) :
                new ObjectParameter("IdVilleRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RES_GetAller1_Result>("RES_GetAller1", dateParameter, idClientParameter, idVilleDepartParameter, idVilleRetourParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> RES_GetPrixTotal1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("RES_GetPrixTotal1", idReservationParameter);
        }
    
        public virtual ObjectResult<RES_GetResByClientId1_Result> RES_GetResByClientId1(Nullable<int> idClient)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RES_GetResByClientId1_Result>("RES_GetResByClientId1", idClientParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> RES_GetResId1(Nullable<int> idClient, Nullable<int> idPlanning)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("RES_GetResId1", idClientParameter, idPlanningParameter);
        }
    
        public virtual int RES_Insert1(Nullable<int> idClient, Nullable<int> idPlanning)
        {
            var idClientParameter = idClient.HasValue ?
                new ObjectParameter("IdClient", idClient) :
                new ObjectParameter("IdClient", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_Insert1", idClientParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<RES_SelectReservationResId_Result> RES_SelectReservationResId(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RES_SelectReservationResId_Result>("RES_SelectReservationResId", idReservationParameter);
        }
    
        public virtual int RES_UpdateReservationResId1(Nullable<int> idReservation)
        {
            var idReservationParameter = idReservation.HasValue ?
                new ObjectParameter("IdReservation", idReservation) :
                new ObjectParameter("IdReservation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RES_UpdateReservationResId1", idReservationParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<VOL_FiltreString_Result> VOL_FiltreString(string champ)
        {
            var champParameter = champ != null ?
                new ObjectParameter("Champ", champ) :
                new ObjectParameter("Champ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_FiltreString_Result>("VOL_FiltreString", champParameter);
        }
    
        public virtual ObjectResult<VOL_GetCaParAge1_Result> VOL_GetCaParAge1(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_GetCaParAge1_Result>("VOL_GetCaParAge1", idVolParameter, idPlanningParameter);
        }
    
        public virtual ObjectResult<Vol_GetInfos_Result> Vol_GetInfos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Vol_GetInfos_Result>("Vol_GetInfos");
        }
    
        public virtual ObjectResult<Nullable<int>> VOL_PLA_GetNbPlacesRestantesNEW1(Nullable<int> idVol, Nullable<int> idPlanning)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VOL_PLA_GetNbPlacesRestantesNEW1", idVolParameter, idPlanningParameter);
        }
    
        public virtual int VOL_PLA_GetStats(Nullable<int> idVol, Nullable<int> idPlanning, ObjectParameter nbPassagers, ObjectParameter nbPlacesRestantes, ObjectParameter tauxOccupation, ObjectParameter ca)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VOL_PLA_GetStats", idVolParameter, idPlanningParameter, nbPassagers, nbPlacesRestantes, tauxOccupation, ca);
        }
    
        public virtual ObjectResult<VOL_SelectAll_Result> VOL_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_SelectAll_Result>("VOL_SelectAll");
        }
    
        public virtual ObjectResult<VOL_SelectAllListChoix1_Result> VOL_SelectAllListChoix1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_SelectAllListChoix1_Result>("VOL_SelectAllListChoix1");
        }
    
        public virtual ObjectResult<VOL_SelectAllListChoixRetour1_Result> VOL_SelectAllListChoixRetour1(Nullable<int> idVilleDepart, Nullable<int> idVilleRetour)
        {
            var idVilleDepartParameter = idVilleDepart.HasValue ?
                new ObjectParameter("IdVilleDepart", idVilleDepart) :
                new ObjectParameter("IdVilleDepart", typeof(int));
    
            var idVilleRetourParameter = idVilleRetour.HasValue ?
                new ObjectParameter("IdVilleRetour", idVilleRetour) :
                new ObjectParameter("IdVilleRetour", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VOL_SelectAllListChoixRetour1_Result>("VOL_SelectAllListChoixRetour1", idVilleDepartParameter, idVilleRetourParameter);
        }
    
        public virtual ObjectResult<PLA_GetDateByVolId2_Result> PLA_GetDateByVolId2(Nullable<int> idVol)
        {
            var idVolParameter = idVol.HasValue ?
                new ObjectParameter("IdVol", idVol) :
                new ObjectParameter("IdVol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PLA_GetDateByVolId2_Result>("PLA_GetDateByVolId2", idVolParameter);
        }
    }
}
