//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Accompagnateur = new HashSet<Accompagnateur>();
            this.AllerRetour = new HashSet<AllerRetour>();
            this.AllerRetour1 = new HashSet<AllerRetour>();
        }
    
        public int RES_ID { get; set; }
        public Nullable<double> RES_PRIX { get; set; }
        public int RES_PLAN_ID { get; set; }
        public int RES_CLIENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accompagnateur> Accompagnateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllerRetour> AllerRetour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllerRetour> AllerRetour1 { get; set; }
        public virtual Client Client { get; set; }
        public virtual Planning Planning { get; set; }
    }
}
