//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranche
    {
        public int TRA_ID { get; set; }
        public int TRA_LIM_INF { get; set; }
        public int TRA_LIM_SUP { get; set; }
        public int TRA_PRIX { get; set; }
        public int TRA_VOL_ID { get; set; }
        public System.DateTime TRA_PERIODE_DEB { get; set; }
        public System.DateTime TRA_PERIODE_FIN { get; set; }
    
        public virtual Vol Vol { get; set; }
    }
}
